services:
  db:
    image: postgres:16
    container_name: smartstock_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartstock
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: smartstock_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/smartstock

volumes:
  postgres_data: