"""Add telegram_link_tokens table

Revision ID: 39383b39d98c
Revises: 40cc57264850
Create Date: 2026-03-24 20:36:07.005304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39383b39d98c'
down_revision: Union[str, Sequence[str], None] = '40cc57264850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_link_token')
    op.drop_column('users', 'telegram_link_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_link_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('telegram_link_token', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
