"""Add telegram link token columns

Revision ID: 40cc57264850
Revises: c22ec8779321
Create Date: 2026-03-24 18:43:41.161750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cc57264850'
down_revision: Union[str, Sequence[str], None] = 'c22ec8779321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_link_token', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('telegram_link_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_link_expires_at')
    op.drop_column('users', 'telegram_link_token')
    # ### end Alembic commands ###
