"""initial_full_schema

Revision ID: 428ca5862a13
Revises: 9aa33c38f24c
Create Date: 2026-01-16 17:24:20.792920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428ca5862a13'
down_revision: Union[str, Sequence[str], None] = '9aa33c38f24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_delivery_product_dt', 'delivery_ts', ['product_id', 'dt'], unique=False)
    op.create_index('idx_predicted_sales_product_dt', 'predicted_sales_ts', ['product_id', 'dt'], unique=False)
    op.drop_index(op.f('idx_price_ts_product_dt'), table_name='price_ts')
    op.create_index('idx_prices_product_dt', 'price_ts', ['product_id', 'dt'], unique=False)
    op.drop_index(op.f('idx_features_dt'), table_name='product_features_daily')
    op.create_index('idx_features_product_dt', 'product_features_daily', ['product_id', 'dt'], unique=False)
    op.drop_index(op.f('idx_sales_proxy_dt'), table_name='sales_proxy_ts')
    op.create_index('idx_sales_product_dt', 'sales_proxy_ts', ['product_id', 'dt'], unique=False)
    op.create_index('idx_social_product_dt', 'social_ts', ['product_id', 'dt'], unique=False)
    op.drop_index(op.f('idx_stock_dt'), table_name='stock_ts')
    op.create_index('idx_stock_product_dt', 'stock_ts', ['product_id', 'dt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_product_dt', table_name='stock_ts')
    op.create_index(op.f('idx_stock_dt'), 'stock_ts', ['dt'], unique=False)
    op.drop_index('idx_social_product_dt', table_name='social_ts')
    op.drop_index('idx_sales_product_dt', table_name='sales_proxy_ts')
    op.create_index(op.f('idx_sales_proxy_dt'), 'sales_proxy_ts', ['dt'], unique=False)
    op.drop_index('idx_features_product_dt', table_name='product_features_daily')
    op.create_index(op.f('idx_features_dt'), 'product_features_daily', ['dt'], unique=False)
    op.drop_index('idx_prices_product_dt', table_name='price_ts')
    op.create_index(op.f('idx_price_ts_product_dt'), 'price_ts', ['product_id', 'dt'], unique=False)
    op.drop_index('idx_predicted_sales_product_dt', table_name='predicted_sales_ts')
    op.drop_index('idx_delivery_product_dt', table_name='delivery_ts')
    # ### end Alembic commands ###
