"""Add updated_at to products table

Revision ID: 89965a66f462
Revises: 0e33d9ba6f4c
Create Date: 2026-03-17 19:31:25.619661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89965a66f462'
down_revision: Union[str, Sequence[str], None] = '0e33d9ba6f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_log',
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', name='task_status'), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at')
    op.drop_table('system_log')
    # ### end Alembic commands ###
