"""initial_migration

Revision ID: 9aa33c38f24c
Revises: 
Create Date: 2026-01-15 16:40:22.687056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa33c38f24c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_pro', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('delivery_ts',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predicted_sales_ts',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('predicted_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_ts',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('price_sale', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_ts_product_dt', 'price_ts', ['product_id', 'dt'], unique=False)
    op.create_table('product_features_daily',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('feedbacks', sa.Integer(), nullable=False),
    sa.Column('avg_sales_7d', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_sales_14d', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_left', sa.Integer(), nullable=False),
    sa.Column('days_to_oos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_rank_in_category', sa.Integer(), nullable=False),
    sa.Column('rating_rank_in_category', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_features_dt', 'product_features_daily', ['dt'], unique=False)
    op.create_table('sales_proxy_ts',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('sales', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sales_proxy_dt', 'sales_proxy_ts', ['dt'], unique=False)
    op.create_table('social_ts',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('feedbacks', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_ts',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_dt', 'stock_ts', ['dt'], unique=False)
    op.create_table('user_favorites',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorites')
    op.drop_index('idx_stock_dt', table_name='stock_ts')
    op.drop_table('stock_ts')
    op.drop_table('social_ts')
    op.drop_index('idx_sales_proxy_dt', table_name='sales_proxy_ts')
    op.drop_table('sales_proxy_ts')
    op.drop_index('idx_features_dt', table_name='product_features_daily')
    op.drop_table('product_features_daily')
    op.drop_index('idx_price_ts_product_dt', table_name='price_ts')
    op.drop_table('price_ts')
    op.drop_table('predicted_sales_ts')
    op.drop_table('delivery_ts')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
