"""Fix user_favorites foreign key to users.id

Revision ID: 9b46d86d8460
Revises: 89965a66f462
Create Date: 2026-03-17 21:14:27.162432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b46d86d8460'
down_revision: Union[str, Sequence[str], None] = '89965a66f462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_favorites_user_id_fkey'), 'user_favorites', type_='foreignkey')
    op.create_foreign_key(None, 'user_favorites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_favorites', type_='foreignkey')
    op.create_foreign_key(op.f('user_favorites_user_id_fkey'), 'user_favorites', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
