"""Fix money fields types (price_sale float, confidence float)

Revision ID: c22ec8779321
Revises: 9b46d86d8460
Create Date: 2026-03-24 15:21:44.588803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c22ec8779321'
down_revision: Union[str, Sequence[str], None] = '9b46d86d8460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Изменяем типы денежных полей
    op.alter_column('price_ts', 'price_sale',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    
    op.alter_column('sales_proxy_ts', 'confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    
    op.alter_column('system_log', 'payload',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    
    # 2. Обновляем user_favorites.user_id: сопоставляем users.user_id с users.id
    # Для записей, где user_id — это Telegram ID, находим соответствующий users.id
    op.execute("""
        UPDATE user_favorites uf
        SET user_id = u.id
        FROM users u
        WHERE uf.user_id = u.user_id
    """)
    
    # 3. Создаём новое FK на users.id (предыдущая миграция уже удалила старое FK)
    op.create_foreign_key(None, 'user_favorites', 'users', ['user_id'], ['id'])
    
    # 4. Удаляем updated_at из products (не использовался)
    op.drop_column('products', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_favorites', type_='foreignkey')
    op.alter_column('system_log', 'payload',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sales_proxy_ts', 'confidence',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=False)
    op.add_column('products', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('price_ts', 'price_sale',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
