"""recomedations

Revision ID: d708a92c8d23
Revises: d70d1fe227ce
Create Date: 2026-04-08 18:19:21.033883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd708a92c8d23'
down_revision: Union[str, Sequence[str], None] = 'd70d1fe227ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_recommendations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='NOW()', nullable=False),
    sa.Column('category', sa.Text(), nullable=True, comment='Категория рекомендации: campaign, keyword, budget, strategy'),
    sa.Column('recommendation_text', sa.Text(), nullable=False, comment='Текст рекомендации от LLM'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Приоритет: 1 = высокий, 2 = средний, 3 = низкий'),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='Дополнительные данные (JSON) — бюджет, ключевые слова и т.д.'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_recommendations_product_id'), 'ad_recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_ad_recommendations_user_id'), 'ad_recommendations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_recommendations_user_id'), table_name='ad_recommendations')
    op.drop_index(op.f('ix_ad_recommendations_product_id'), table_name='ad_recommendations')
    op.drop_table('ad_recommendations')
    # ### end Alembic commands ###
