"""add_unique_constraint_to_ts

Revision ID: ee37e07d89f5
Revises: 428ca5862a13
Create Date: 2026-01-24 13:00:04.885999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee37e07d89f5'
down_revision: Union[str, Sequence[str], None] = '428ca5862a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_delivery_product_dt'), table_name='delivery_ts')
    op.create_unique_constraint('uq_delivery_product_dt', 'delivery_ts', ['product_id', 'dt'])
    op.drop_index(op.f('idx_predicted_sales_product_dt'), table_name='predicted_sales_ts')
    op.create_unique_constraint('uq_predicted_sales_product_dt', 'predicted_sales_ts', ['product_id', 'dt'])
    op.drop_index(op.f('idx_prices_product_dt'), table_name='price_ts')
    op.create_unique_constraint('uq_prices_product_dt', 'price_ts', ['product_id', 'dt'])
    op.drop_index(op.f('idx_features_product_dt'), table_name='product_features_daily')
    op.create_unique_constraint('uq_features_product_dt', 'product_features_daily', ['product_id', 'dt'])
    op.drop_index(op.f('idx_sales_product_dt'), table_name='sales_proxy_ts')
    op.create_unique_constraint('uq_sales_product_dt', 'sales_proxy_ts', ['product_id', 'dt'])
    op.drop_index(op.f('idx_social_product_dt'), table_name='social_ts')
    op.create_unique_constraint('uq_social_product_dt', 'social_ts', ['product_id', 'dt'])
    op.drop_index(op.f('idx_stock_product_dt'), table_name='stock_ts')
    op.create_unique_constraint('uq_stock_product_dt', 'stock_ts', ['product_id', 'dt'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_stock_product_dt', 'stock_ts', type_='unique')
    op.create_index(op.f('idx_stock_product_dt'), 'stock_ts', ['product_id', 'dt'], unique=False)
    op.drop_constraint('uq_social_product_dt', 'social_ts', type_='unique')
    op.create_index(op.f('idx_social_product_dt'), 'social_ts', ['product_id', 'dt'], unique=False)
    op.drop_constraint('uq_sales_product_dt', 'sales_proxy_ts', type_='unique')
    op.create_index(op.f('idx_sales_product_dt'), 'sales_proxy_ts', ['product_id', 'dt'], unique=False)
    op.drop_constraint('uq_features_product_dt', 'product_features_daily', type_='unique')
    op.create_index(op.f('idx_features_product_dt'), 'product_features_daily', ['product_id', 'dt'], unique=False)
    op.drop_constraint('uq_prices_product_dt', 'price_ts', type_='unique')
    op.create_index(op.f('idx_prices_product_dt'), 'price_ts', ['product_id', 'dt'], unique=False)
    op.drop_constraint('uq_predicted_sales_product_dt', 'predicted_sales_ts', type_='unique')
    op.create_index(op.f('idx_predicted_sales_product_dt'), 'predicted_sales_ts', ['product_id', 'dt'], unique=False)
    op.drop_constraint('uq_delivery_product_dt', 'delivery_ts', type_='unique')
    op.create_index(op.f('idx_delivery_product_dt'), 'delivery_ts', ['product_id', 'dt'], unique=False)
    # ### end Alembic commands ###
